[theme]
primaryColor = "#FF3B30"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#EAECEE"
textColor = "#1E1E1E"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true
maxMessageSize = 200
maxUploadSize = 200

[browser]
gatherUsageStats = false

[server.timeout]
app = 300