[theme]
primaryColor = "#FF3B30"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#EAECEE"
textColor = "#1E1E1E"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false