[theme]
# Primary accent color for interactive elements
primaryColor = "#FF3B30"

# Background color for the main content area
backgroundColor = "#FAFAFA"

# Background color used for the sidebar and most interactive widgets
secondaryBackgroundColor = "#EAECEE"

# Color used for almost all text
textColor = "#1E1E1E"

# Font family for all text in the app, except code blocks
font = "sans serif"